services:
  - type: web
    name: fantasy-gpt-coach
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
